import "./globals.css";
import "@radix-ui/themes/styles.css";
import { ThemeProvider } from '@mui/material/styles';
import { Theme } from "@radix-ui/themes";
import localFont from 'next/font/local'
import type { Metadata } from "next";
import QueryProvider from "@/providers/QueryProvider";
import { UserProvider } from "@/providers/UserProvider";
import { getCurrentUser } from "@/lib/auth/aw-auth";
import NavBar from "@/components/navbar/navbar";
import theme from "@/theme/theme";
import CustomToast from "@/components/ui/CustomToast";


const ravi = localFont({
  src:'../../public/fonts/ravi.ttf' , 
  variable: '--font-ravi'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="fa" dir="rtl" >
      <body
        className={`${ravi.variable} text-[#444] antialiased`}
      >
        <UserProvider currentUser={currentUser}>
          <QueryProvider>
           <Theme>
            <ThemeProvider theme={theme}>
              <NavBar/>
              <main className="min-h-screen font-ravi">
               {children}
             </main>
           </ThemeProvider>
          </Theme>
        </QueryProvider>
        </UserProvider>
        <CustomToast />
      </body>
    </html>
  );
}
