import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import localFont from 'next/font/local'
import type { Metadata } from "next";
import QueryProvider from "@/providers/QueryProvider";
import { UserProvider } from "@/providers/UserProvider";
import { getCurrentUser } from "@/packages/lib/prisma/auth/aw-auth";


const iransans = localFont({
  src:'../../public/fonts/iransans.ttf' ,
  variable: '--font-iransans'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser()
  return (
    <html lang="fa" dir="rtl" >
      <body
        className={`${iransans.variable} antialiased`}
      >
        <UserProvider currentUser={currentUser}>
          <QueryProvider>
           <Theme>
            <main>
            {children}
           </main>
          </Theme>
        </QueryProvider>
        </UserProvider>
      </body>
    </html>
  );
}
